"""
wdnkit.ontology
===============
Emits the ABox (instances) for the WDN sensor ontology from the pipeline's own
tables, so the knowledge graph is always consistent with the model that
produced it.

Individuals written:
  network        one WaterDistributionNetwork
  nodes          Junction / DeadEnd / Bend, with elevation, demand, pressure
  pipes          Pipe, with diameter, length, material, Hazen-Williams C
  DMAs           DistrictMeteredArea, one per cluster
  stations       MonitoringStation at each selected node
  sensors        one per configured suite member, per station
  rationale      the criteria each station satisfied, reified
"""

from __future__ import annotations

import datetime as _dt

# hardware catalogue: local name -> (label, property, pin, interface, unit)
SENSOR_CATALOGUE = {
    "pH": ("DFRobot Gravity Analog pH v2", "pH", "A0", "AnalogInterface", "PH"),
    "TDS": ("DFRobot Gravity Analog TDS", "totalDissolvedSolids", "A1",
            "AnalogInterface", "PPM"),
    "DO": ("DFRobot Gravity Analog Dissolved Oxygen", "dissolvedOxygen", "A2",
           "AnalogInterface", "MilliGM-PER-L"),
    "ORP": ("Analog ORP meter, Pt-ring electrode", "oxidationReductionPotential",
            "A3", "AnalogInterface", "MilliV"),
    "Temperature": ("DS18B20 1-Wire temperature probe", "waterTemperature", "D2",
                    "OneWireInterface", "DEG_C"),
    "Turbidity": ("Analog turbidity sensor", "turbidity", "A4",
                  "AnalogInterface", "NTU"),
    "Pressure": ("Piezoresistive pressure transducer", "pressure", "A5",
                 "AnalogInterface", "M-H2O"),
    "Flow": ("Hall-effect flow meter", "flowRate", "D3",
             "PulseInterface", "L-PER-SEC"),
}

CRITERIA = {
    "f1_topology": "C1_JunctionOrDeadEnd",
    "f2_elevation": "C2_ElevationAboveMean",
    "f3_pressure": "C3_PressureTail",
    "f4_demand": "C4_DemandAboveMean",
}

HEADER = """@prefix wdn:  <{ns}> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix sosa: <http://www.w3.org/ns/sosa/> .
@prefix ssn:  <http://www.w3.org/ns/ssn/> .
@prefix geo:  <http://www.opengis.net/ont/geosparql#> .
@prefix unit: <http://qudt.org/vocab/unit/> .
@prefix dcterms: <http://purl.org/dc/terms/> .

# ABox generated by wdnkit on {stamp}
# network: {name}  |  {n_nodes} nodes, {n_pipes} pipes, {n_dma} DMAs, {n_st} stations
"""


def _lit(v, typ="decimal"):
    return f'"{v}"^^xsd:{typ}'


def emit(nodes, pipes, sel, cfg, meta, path, crs=None):
    ns = cfg.get("ontology.namespace", "https://w3id.org/iitb/wdn#")
    pfx = cfg.get("ontology.instance_prefix", "") or ""
    name = cfg.get("project.name", "wdn")
    suite = list(cfg.get("ontology.sensor_suite",
                         ["pH", "TDS", "ORP", "DO", "Temperature"]))
    rough = cfg.get("hydraulics.roughness_by_material", {})

    def uri(x):
        return f"wdn:{pfx}{x}"

    L = [HEADER.format(ns=ns, stamp=_dt.datetime.now().isoformat(timespec="seconds"),
                       name=name, n_nodes=len(nodes), n_pipes=len(pipes),
                       n_dma=int(nodes.cluster.nunique()), n_st=len(sel))]

    net = uri(f"Network_{name}")
    L.append(f"""
{net} a wdn:WaterDistributionNetwork ;
    rdfs:label "{name} water distribution network"@en ;
    dcterms:created "{_dt.date.today().isoformat()}"^^xsd:date ;
    wdn:totalPipeLength {_lit(round(float(pipes.length_m.sum()), 1))} ;
    wdn:averageDayDemand {_lit(round(float(meta.get('avg_day_lps', 0)), 4))} ;
    wdn:peakFactor {_lit(cfg.get('demand.peak_factor', 1.0))} .
""")

    # ---- DMAs ------------------------------------------------------------
    for c in sorted(nodes.cluster.unique()):
        sub = nodes[nodes.cluster == c]
        L.append(f"""
{uri(f'DMA_{int(c)}')} a wdn:DistrictMeteredArea ;
    rdfs:label "District metered area {int(c)}"@en ;
    wdn:partOfNetwork {net} ;
    wdn:nodeCount {_lit(len(sub), 'integer')} ;
    wdn:meanElevation {_lit(round(float(sub.elevation_m.mean()), 2))} ;
    wdn:meanPressure {_lit(round(float(sub.pressure_m.mean()), 2))} ;
    wdn:aggregateDemand {_lit(round(float(sub.demand_lps.sum()), 4))} .
""")

    # ---- nodes -----------------------------------------------------------
    cls = {"junction": "wdn:Junction", "dead_end": "wdn:DeadEnd",
           "bend": "wdn:Bend"}
    for _, r in nodes.iterrows():
        wkt = f'"POINT({r.x:.3f} {r.y:.3f})"^^geo:wktLiteral'
        L.append(f"""
{uri(r.node_id)} a {cls.get(r.node_type, 'wdn:Junction')} ;
    wdn:nodeIdentifier "{r.node_id}" ;
    wdn:partOfNetwork {net} ;
    wdn:inDMA {uri(f'DMA_{int(r.cluster)}')} ;
    wdn:elevation {_lit(round(float(r.elevation_m), 2))} ;
    wdn:baseDemand {_lit(round(float(r.demand_lps), 5))} ;
    wdn:modelledPressure {_lit(round(float(r.pressure_m), 2))} ;
    wdn:nodeDegree {_lit(int(r.degree), 'integer')} ;
    geo:asWKT {wkt} .""")
        for col, crit in CRITERIA.items():
            if bool(r.get(col, False)):
                L.append(f"{uri(r.node_id)} wdn:satisfiesCriterion wdn:{crit} .")

    # ---- pipes -----------------------------------------------------------
    for _, r in pipes.iterrows():
        mat = str(r.material)
        L.append(f"""
{uri(r.pipe_id)} a wdn:Pipe ;
    wdn:nodeIdentifier "{r.pipe_id}" ;
    wdn:partOfNetwork {net} ;
    wdn:startNode {uri(r.node1)} ;
    wdn:endNode {uri(r.node2)} ;
    wdn:pipeLength {_lit(round(float(r.length_m), 2))} ;
    wdn:diameter {_lit(round(float(r.diameter_mm), 1))} ;
    wdn:hazenWilliamsC {_lit(rough.get(mat, rough.get('UNK', 110.0)))} ;
    wdn:hasMaterial wdn:{_material_ind(mat)} .""")
        if "diameter_cad_mm" in pipes.columns:
            L.append(f"{uri(r.pipe_id)} wdn:cadDiameter "
                     f"{_lit(round(float(r.diameter_cad_mm), 1))} .")

    # ---- stations, sensors, rationale ------------------------------------
    for _, r in sel.iterrows():
        st = uri(f"Station_{r.node_id}")
        L.append(f"""
{st} a wdn:MonitoringStation ;
    rdfs:label "Monitoring station at {r.node_id}"@en ;
    wdn:deployedAt {uri(r.node_id)} ;
    wdn:monitors {uri(r.node_id)} ;
    wdn:inDMA {uri(f'DMA_{int(r.cluster)}')} ;
    wdn:samplingIntervalSeconds {_lit(60, 'integer')} .""")

        for flag in str(r.get("risk_flags", "None")).split("|"):
            if flag and flag != "None":
                L.append(f"{st} wdn:addressesRisk wdn:{flag} .")

        rat = uri(f"Rationale_{r.node_id}")
        L.append(f"""
{rat} a wdn:PlacementRationale ;
    rdfs:comment "{str(r.selection_reason)[:400]}"@en ;
    wdn:criterionValue {_lit(round(float(r.elevation_m), 2))} .
{st} wdn:hasRationale {rat} .""")
        for col, crit in CRITERIA.items():
            if bool(r.get(col, False)):
                L.append(f"{rat} wdn:satisfiesCriterion wdn:{crit} .")

        for s in suite:
            if s not in SENSOR_CATALOGUE:
                continue
            label, prop, pin, iface, unit = SENSOR_CATALOGUE[s]
            sid = uri(f"Sensor_{r.node_id}_{s}")
            L.append(f"""
{sid} a wdn:{s if s != 'pH' else 'PH'}Sensor , sosa:Sensor ;
    rdfs:label "{label}"@en ;
    sosa:observes wdn:{prop} ;
    wdn:mcuPin "{pin}" ;
    wdn:usesInterface wdn:{iface} ;
    wdn:hasUnit unit:{unit} .
{st} sosa:hosts {sid} .""")
            if s in ("pH", "TDS", "DO") and "Temperature" in suite:
                L.append(f"{sid} wdn:compensatedBy "
                         f"{uri(f'Sensor_{r.node_id}_Temperature')} .")

    text = "\n".join(L) + "\n"
    with open(path, "w") as f:
        f.write(text)
    return path, len(L)


def _material_ind(mat: str) -> str:
    return {"CI": "CastIron", "GI": "GalvanisedIron", "DI": "DuctileIron",
            "PVC": "PVC", "HDPE": "HDPE", "MS": "MildSteel"}.get(
        str(mat).upper(), "UnknownMaterial")
